set -g default-command zsh

unbind q
bind q command-prompt -p "Kill-session: Y(enter) | n(escape)" \
       "run \"tmux list-panes -a -F '##{session_name}:##{window_index}.##{pane_index}' \
              | xargs -I PANE tmux send-keys -t PANE 'C-c' ; tmux kill-session \""


set -g mouse on

set -g history-limit 10000
set -sg escape-time 0

# Start windows and panes at 1, not 0
set -g base-index 1
setw -g pane-base-index 1

bind -n M-h select-pane -L
bind -n M-j select-pane -D
bind -n M-k select-pane -U
bind -n M-l select-pane -R

set-option -g status-position top
