[opener]
edit = [
	{ run = 'nvim "$@"', block = true },
]
play = [
	{ run = 'mpv "$@"', orphan = true, for = "unix" },
]
open = [
	{ run = 'xdg-open "$@"', desc = "Open" },
]
pdff = [
	{ run = 'brave-browser "$@"', desc = "open pdf in brave", block = true, for = "unix" },
	]
